### ISSUE TITLE
Error on page

### ISSUE THREAD

**Issue by jumper423** [phalcon/docs#1033]
https://docs.phalconphp.com/en/3.2/installation/en/download
```
Not-Found handler is not callable or is not defined 
#0 .../app/library/Main.php(274): Phalcon\Mvc\Micro->handle() 
#1 .../app/library/Main.php(158): Docs\Main->runApplication() 
#2 .../public/index.php(16): Docs\Main->run(Object(Phalcon\Di\FactoryDefault)) 
#3 {main}
```

**Comment by sergeyklay** [comment]
I'll try to sort out ASAP.

**Comment by sergeyklay** [comment]
Fixed. Feel free to open new issue if the problem appears again. Thank you for contributing.
